### ISSUE TITLE
[TODO] 기능 복구 예정

### ISSUE THREAD

**Issue by joonas-yoon** [joonas-yoon/boj-extended#103]
#101 에서 [#80 - 일부 기능 미지원](https://github.com/joonas-yoon/boj-extended/issues/80) 이슈를 해결하였기 때문에, 기능을 다시 복구해야함.

- [x] Deprecated annotation 지우기
- [x] 유저 VS 페이지 복구 
- - https://github.com/joonas-yoon/boj-extended/commit/7aeb8d58ae94a96171020f264d720e4993a4648b
- - #12
- [x] 게시글 개수 표시
- - https://github.com/joonas-yoon/boj-extended/commit/6920092a3f32995cdb85e07eeddde76ff64c995e
- - https://github.com/joonas-yoon/boj-extended/commit/5986679aed93969db787055759d54c08199c6bd3
- [x] 문제 해결 여부에 따른 색상 표시
- - [x] #44
- - [x] #54
- - [x] #61
- - https://github.com/joonas-yoon/boj-extended/commit/994180e9440329fd07bc4ba865354e58ec5a6406
- - https://github.com/joonas-yoon/boj-extended/commit/95cd0f5c2b2cb2cfc6322024fdc092929f8d9a1f

---

will be back. 👍 

![](https://t1.daumcdn.net/cfile/tistory/17159D3A512DE8E017)
